<?php

/**
 * @file
 * Main file for the vinvit module.
 */

/**
 * Implements hook_theme().
 */
function vinvit_theme(): array
{
  $themes['cats'] = [
    "variables" => [
      'add_form' => NULL,
      'markup' => NULL,
      'cats' => NUll,
    ]
  ];
  $themes['cats-list'] = [
    "variables" => [
      'markup' => NULL,
      'cats' => NUll,
    ]
  ];
  return $themes;
}

 /**
 * Implements hook_page_attachments().
 */
function vinvit_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'vinvit/vinvit';
}
